### ISSUE TITLE
New obfuscator

### ISSUE THREAD

**Issue by mithuncoder** [xKiian/Hyperion-deobfuscator#1]
Yeah

**Comment by sfx2me** [comment]
are you the guy from pyobfuscate.com?

**Comment by mithuncoder** [comment]
Yes

**Comment by sfx2me** [comment]
its not bad

**Comment by sfx2me** [comment]
![image](https://user-images.githubusercontent.com/88455386/212564940-eb117b2a-06a8-41c4-b090-c7661e8cbcae.png)

i can kinda see the code
but not fully

**Comment by sfx2me** [comment]
not bad

**Comment by sfx2me** [comment]
why did you delete the repo? lol
