### ISSUE TITLE
NameError: name 'XWWXWWWWXWWWWWWXX' is not defined

### ISSUE THREAD

**Issue by KhanhNguyen9872** [xKiian/Hyperion-deobfuscator#12]
File: [getcookie.zip](https://github.com/xKiian/Hyperion-deobfuscator/files/11790817/getcookie.zip)

![image](https://github.com/xKiian/Hyperion-deobfuscator/assets/88880309/e1acd822-d943-45d2-a96a-f0ab72eb215d)

**Comment by KhanhNguyen9872** [comment]
if this script cannot deobfuscate Hyperion, try it [here](https://github.com/KhanhNguyen9872/hyperion_deobfuscate)

**Comment by xKiian** [comment]
why are you spreading malware?
